name: Aspect Workflows Warming

on:
    # Run the workflows on a cron schedule to periodically create an up-to-date warming archive
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    schedule:
        - cron: '0 8 * * *'

    # Allow this to be triggered manually via the GitHub UI Actions tab
    workflow_dispatch:

# NB: Setting RUNNER_TRACKER_ID="" in the Agent health check sets prevents GitHub Actions from
# killing the Bazel server started during health check when "Cleaning up orphan processes" in the
# "Complete job" step. See https://github.com/actions/runner/issues/598 for more info.

jobs:
    warming-archive:
        name: Aspect Workflows Warming
        runs-on: [self-hosted, aspect-workflows, aspect-warming]
        steps:
            - name: Workflows environment
              run: /etc/aspect/workflows/bin/configure_workflows_env
            - uses: actions/checkout@v4
            - name: Agent health check
              run: RUNNER_TRACKER_ID="" && /etc/aspect/workflows/bin/agent_health_check
            - name: Create warming archive
              run: rosetta run warming
            - name: Archive warming tars
              run: /etc/aspect/workflows/bin/warming_archive
